// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js keeps local secrets in .env.local. Prisma CLI does not load that
// file automatically, so load it explicitly for db pull/migrate/deploy.
loadEnv({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7 moved connection URLs from schema.prisma into this config.
    // Use the session-mode pooler for migrations and introspection.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
